name: shorne in japan
highlighter: rouge
github: [Repository metadata]
safe: true
lsi: false
paginate: 5
url: "http://stffrdhrn.github.io"
plugins:
 - jekyll-sitemap
 - jekyll-paginate
 - jekyll-feed

title: shorne in japan
description: Stafford's blog about engineering and software
author: Stafford Horne
timezone: Europe/London
